[tools]
ast-grep = "latest"
bun = "1.3.14"

[tasks.install-local]
description = "Install the current code locally as a binary"
usage = ""
run = "bun build --compile --target=bun --no-compile-autoload-dotenv --outfile=$(which kit) src/main.js"

[tasks.release]
description = "Build cross-platform kit binaries and upload them to a GitHub release"
usage = "arg <version>"
run = "bun scripts/release.js $usage_version"
