import { Glob } from 'bun'

/**
 * KitProviderProvider manages Kit provider modules under providers/<name>/index.js.
 */
class KitProviderProvider {
	constructor(kit) {
		this.kit = kit
	}

	name() {
		return 'kit-provider'
	}

	async *types() {
		yield new KitProviderType(this.kit)
	}

	async *components() {
		const root = this.kit.FileURI.fromPath('providers')

		for await (const path of new Glob('*/index.js').scan({ cwd: 'providers' })) {
			yield new KitProviderComponent({ path: root.join(path).path(), kit: this.kit })
		}
	}

	create(spec, env) {
		return new KitProviderType(this.kit).create(spec, env)
	}
}

/**
 * KitProviderType describes how to generate a new Kit provider skeleton.
 */
class KitProviderType {
	constructor(kit) {
		this.kit = kit
	}

	id() {
		return 'provider'
	}

	description() {
		return 'A Kit provider module in providers/<name>/index.js'
	}

	schema() {
		const { Type } = this.kit

		return Type.Object({
			name: Type.String({
				description:
					'Kebab-case provider name without the kit- prefix unless it is part of the name',
				examples: ['sveltekit', 'database', 'kit-widget'],
				pattern: '^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$',
			}),
			description: Type.String({
				description: 'Short user-facing description of the provider',
				examples: ['Generate SvelteKit routes and remote functions'],
			}),
			project: Type.Optional(
				Type.String({
					description:
						'Directory to generate the provider into; defaults to <repo-root>/providers',
					examples: ['providers', '.kit/providers'],
				}),
			),
		})
	}

	parse(argv) {
		return this.kit.parseArgs({
			args: argv,
			options: this.kit.parseArgsOptionsFromSchema(this.schema()),
			strict: true,
			allowPositionals: true,
		})
	}

	describe(spec) {
		return spec.description
	}

	async *create(spec, env) {
		const base = spec.project ?? (await this.kit.repoRoot()).join('providers').path()
		const root = this.kit.FileURI.fromPath(base)
		const path = root.join(spec.name, 'index.js').path()

		yield await env.createFile(path, providerTemplate(spec))
		yield this.kit.Event.plan(
			`Finish generated ${spec.name} provider`,
			[
				{
					id: 'analyze-provider-domain',
					instructions: 'Analyze the target domain and summarize implementation requirements',
					files: [path],
					agent: {
						prompt: analysisPrompt(spec, path),
					},
				},
				{
					id: 'fill-in-provider',
					instructions: 'Use Amp to finish generated provider implementation',
					files: [path],
					agent: {
						prompt: providerPrompt(spec, path),
					},
				},
				{
					id: 'verify-provider',
					instructions: 'Verify generated provider is discovered',
					verifyWithCommand: 'bun run kit provider list',
				},
			],
			{ intent: spec.intent },
		)
	}
}

/**
 * KitProviderComponent represents one provider module already present in the checkout.
 */
class KitProviderComponent {
	constructor({ path, kit }) {
		this.path = path
		this.kit = kit
	}

	provider() {
		return 'kit-provider'
	}

	id() {
		return providerName(this.kit.FileURI.fromPath(this.path))
	}

	description() {
		return `Kit provider ${this.id()}`
	}

	inspect() {
		return {
			name: this.id(),
			files: [this.path],
		}
	}
}

function providerName(file) {
	return file.parent().relativeTo(file.parent().parent())
}

function providerTemplate(spec) {
	return `/**
 * ${spec.name} provider exposes ${spec.description} components to Kit.
 */
class ${className(spec.name)}Provider {
	constructor(kit) {
		this.kit = kit
	}

	name() {
		return ${JSON.stringify(spec.name)}
	}

	async *types() {
		yield new ${className(spec.name)}Type(this.kit)
	}

	async *components() {}

	create(spec, env) {
		return new ${className(spec.name)}Type(this.kit).create(spec, env)
	}
}

/**
 * ${className(spec.name)}Type describes components generated by ${spec.name}.
 */
class ${className(spec.name)}Type {
	constructor(kit) {
		this.kit = kit
	}

	id() {
		return 'component'
	}

	description() {
		return ${JSON.stringify(spec.description)}
	}

	schema() {
		const { Type } = this.kit

		return Type.Object({
			name: Type.String({ description: 'Generated component name' }),
		})
	}

	parse(argv) {
		return this.kit.parseArgs({
			args: argv,
			options: this.kit.parseArgsOptionsFromSchema(this.schema()),
			strict: true,
			allowPositionals: true,
		})
	}

	describe(spec) {
		return spec.name
	}

	async *create(spec, env) {
		throw new Error('${spec.name} does not create components yet')
	}
}

export default function provider(kit) {
	return new ${className(spec.name)}Provider(kit)
}
`
}

function analysisPrompt(spec, path) {
	return `Intent: ${spec.intent ?? spec.description}

Analyze what the generated ${spec.name} provider in ${path} must implement.
The implementation agent may not have Kit source access, so produce a concise,
self-contained summary of:
- component ids and descriptions to expose
- files/directories to scan
- algorithms needed for discovery
- ast-grep commands or patterns needed
- generated provider contract details it must preserve
Do not edit files in this analysis step.`
}

function providerPrompt(spec, path) {
	return `Intent: ${spec.intent ?? spec.description}

Finish the generated ${spec.name} provider in ${path}.
Use the injected kit runtime object; do not import Kit internals from provider code.
Inspect unfamiliar APIs dynamically with kit.methods(), kit.method(name).signature(),
kit.method(name).source(), env.methods(), and env.method(name).parameterNames().
If you need to inspect the Kit API outside provider execution, use bun run kit repl.
The provider module must default-export function provider(kit) and return an object with:
- name(): provider name string
- async *types(): yields component type objects
- async *components(): yields existing component objects
- create(spec, env): delegates generation to a component type

Component type objects must implement:
- id(): component type id
- description(): user-facing type description
- schema(): TypeBox schema using kit.Type
- parse(argv): kit.parseArgs with kit.parseArgsOptionsFromSchema(this.schema())
- describe(spec): concise generated component description
- async *create(spec, env): calls env.createFile/editFile and yields kit.Event file/plan events

Component objects must implement:
- provider(): provider name
- id(): component id within provider
- description(): user-facing component description
- inspect(): structured fields including files when applicable

Available injected kit helpers include Type, Event, FileURI, Identifier, parseArgs,
parseArgsOptionsFromSchema, TableFormatter, and PlanFormatter.
Do not refactor unrelated code.`
}

function className(name) {
	return name
		.split('-')
		.map((part) => part[0].toUpperCase() + part.slice(1))
		.join('')
}

export default function provider(kit) {
	return new KitProviderProvider(kit)
}
